### ISSUE TITLE
Battery widget doesn't work and netspeed doesn't change

### ISSUE THREAD

**Issue by qbnil** [tribhuwan-kumar/artimux#1]
First of all, thx for this awesome config bud, you really put a lot of work into it, keep it up...
There are some issues i stumbled upon after i started using this plugin:
1) The battery widget doesnt show up in status bar
![image](https://github.com/tribhuwan-kumar/Artimux/assets/130576530/084313de-0e2a-4550-ba9c-715689290ba7)
-> This is the error i get after running the actual file:
![image](https://github.com/tribhuwan-kumar/Artimux/assets/130576530/9f3c8054-27f6-4b5a-b80b-897656e85f1c)
2) The netspeed is always at 0, no matter what
![image](https://github.com/tribhuwan-kumar/Artimux/assets/130576530/a3a1c42e-8ef6-46c3-b00e-b755d642175f)

**Comment by qbnil** [comment]
Update... i managed to fix the netspeed widget by changing the interface adapter in tmux.conf

**Comment by qbnil** [comment]
Second update... fixed the battery widget by adding this to tmux.conf - didn't find this in your readme tho - set -g @Artimux_show_battery "true", you should make sure to include this too

**Comment by tribhuwan-kumar** [comment]
I forgot to updating this repo since I'm working on other projects, but thanks for figuring out yourself!
